Raise error when specifying transformation without bounds
emdgroup/baybe pull request #451
Opened 2024-12-10 08:32 UTC by AVHopp

This PR fixes #449 by now checking whether a `NumericalTarget` has bounds if a transformation is provided.

Introduces a new step in the validation, raising a value error if the user provides a transformation but no bounds. Also adds an according test.

2024-12-10 10:01 UTC, Scienfitz requested changes

2024-12-10 10:01 UTC, Scienfitz commented on tests/validation/test_target_validation.py
you might have to update hypothesis strategy for targets to incororate the new requirement

2024-12-10 10:01 UTC, Scienfitz requested changes

2024-12-10 10:01 UTC, Scienfitz commented on baybe/targets/numerical.py
please add this to CHANGELOG

2024-12-10 12:12 UTC, AVHopp commented on tests/validation/test_target_validation.py
I had a look at the hypothesis strategy, and this seems to still work. The issue that is fixed here was only happening when you provide a transformation without providing bounds - something that the hypothesis strategy does not do since it is not a reasonable thing to do. The only thing what was missing was the validation/raising a proper error if this happens, so the hypothesis strategy is not affected by that as far as I understand.

2024-12-10 12:15 UTC, AVHopp commented on tests/validation/test_target_validation.py
> +        param("MIN", "LINEAR"),
Added `id`s. Feel free to unresolve if you'd prefer other names.

2024-12-10 12:15 UTC, AVHopp commented on baybe/targets/numerical.py
Done. Feel free to unresolve if you do not like the formulation.

2024-12-10 12:42 UTC, Scienfitz commented on tests/validation/test_target_validation.py
this was just my naive interpretation of this error in the CI: 
![image](https://github.com/user-attachments/assets/6cd46dd1-ebe0-4a4d-945c-19f48ce1cb9d)
where else does it come from?

2024-12-10 12:58 UTC, AVHopp commented on tests/validation/test_target_validation.py
Ok that is weird. I'll have a closer look.

2024-12-10 13:10 UTC, AVHopp commented on tests/validation/test_target_validation.py
You were 100% right. I adjusted the strategy such that the `exclude_fully_unbounded` is set to `True` if either (i) the target mode is  `TargetMode.MATCH` or `transformation is not None`. If I am not mistaken this should fix the strategy, please review and resolve.

2024-12-10 13:28 UTC, Scienfitz approved these changes

2024-12-11 06:58 UTC, AdrianSosic approved these changes
Hi @AVHopp, thanks for the quick fix. I added one commit that fixed a few minor things in the test but apart from that everything was looking good. Feel free to merge 🚀 

That said, there is still the overall problem that we are a bit too restrictive in how we require users to set bounds/transformations, but that's a story for another PR 🙃

2024-12-11 11:14 UTC, merged